### PR TITLE
Feat: add optional heading content to Card

### PR DESCRIPTION
**Pull request by danad02**
Add optional `headingContent` to the Card. It can be anything.

### CODE REVIEW

**Comment by aigoncharov** [comment]
@danad02 could we simplify it a bit and just make `title` prop accept any JSX?

**Comment by danad02** [comment]
@aigoncharov Good idea. How come this idea didn't strike me right away is beyond me. I'm tired probably :smile:

**Comment by danad02** [comment]
@aigoncharov I think that in this case we can also just remove the left side icon. WDYT?

**Comment by aigoncharov** [comment]
> @aigoncharov I think that in this case we can also just remove the left side icon. WDYT?

I am wondering where is the line where we have too much freedom. Probably, even making the title any arbitrary JSX might be too much as it could allow us breaking the design guidelines. What if wekeep the title as a string, but add `headerLeftSlot` prop which would be any JSX. Then we would be able to make sure there are proper padding between the elements. WDYT?

**Comment by danad02** [comment]
@aigoncharov I added it a `headingContent` prop to the Card component. Check it out: https://github.com/hazelcast/frontend-shared/pull/179/commits/6f6646b3ba7da789e2627f650d31eb61c3c6ba0e

**Review by aigoncharov — APPROVED** [review]
LGTM!

**Pull request merged**
