### PR TITLE
fix: icon/iconbutton outline spacing

### LINKED ISSUE #172: [Core UI] Enhance IconButton alignment
See https://github.com/hazelcast/management-center/pull/4172#discussion_r561902594

### PR DESCRIPTION
**Pull request by jankoritak**
Fixes #172

### CODE REVIEW

**Review by danad02 — APPROVED** [review]
LGTM

**Comment by aigoncharov** [comment]
Should we keep icons inline/inline-block/inline-flex to easily insert them in any text?

**Comment by jankoritak** [comment]
> Should we keep icons inline/inline-block/inline-flex to easily insert them in any text?

That's a great point. Addressed.

@danad02, could you please run the visual tests for this PR? 🙏

**Comment by danad02** [comment]
@jankoritak There's a small regression caused by the Icon's <div> element addition:
image
The icons in TextField do not change color when in hovered/focused/error state.

**Comment by jankoritak** [comment]
Wow, that's a great catch! Will look into it, thanks!

**Pull request merged**
