### PR TITLE
Feature/date time picker

### LINKED ISSUE #7: [UI core library] Date/time picker
Zeroheight design is missing!

### PR DESCRIPTION
**Pull request by jankoritak**
Closes #7 

#### Description
- Implements Date/Time picker input, resp. Calendar Input
- The designs slightly differ from Figma - as discussed [over here](https://hazelcast.slack.com/archives/C01BT11F24E/p1613563577124200).
- My apologies for this taking so long, the package's API and it's documentation does not really account for the fastest development, I would advice looking for an alternative should we do something similar in the future. IE11 is also quite a killer.

### CODE REVIEW

**Comment by aigoncharov** [comment]
@jankoritak I have removed `--chromeDockerImage=original` from package.json to fix visual tests

**Comment by aigoncharov** [comment]
@jankoritak 
```
22:08:34 lerna ERR! npm run test:visual stderr:
22:08:34 FAIL chrome.docker/chrome.minimal/Components/Button/Secondary Disabled Tooltip: Screenshot differs from reference, see .loki/difference/chrome_minimal_Components_Button_Secondary_Disabled_Tooltip.png
22:08:34 FAIL chrome.docker/chrome.minimal/Components/Calendar/Default: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/Calendar/Disabled: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/Calendar/Open: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/Calendar/With Time: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/CalendarRange/Default: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/CalendarRange/Start Open: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/CalendarRange/End Open: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/CalendarRange/With Time Inputs: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TextField/With Trailing Icon: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TextField/With Trailing Icon Disabled: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TimeField/Default: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TimeField/Error: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TimeField/Hovered: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TimeField/Focused: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TimeField/Focused With Error: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TimeField/Focused With Hover: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TimeField/Disabled: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TimeField/With Seconds: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/TimeField/Time Field Wrapped In Formik: No reference image found
22:08:34 FAIL chrome.docker/chrome.minimal/Components/Tooltip/Left Placement: Screenshot differs from reference, see .loki/difference/chrome_minimal_Components_Tooltip_Left_Placement.png
22:08:34 FAIL chrome.docker/chrome.minimal/Components/Tooltip/Left Start Placement: Screenshot differs from reference, see .loki/difference/chrome_minimal_Components_Tooltip_Left_Start_Placement.png
22:08:34 FAIL chrome.docker/chrome.minimal/Components/Tooltip/Left End Placement: Screenshot differs from reference, see .loki/difference/chrome_minimal_Components_Tooltip_Left_End_Placement.png
22:08:34 FAIL chrome.docker/TESTS: Some tasks failed to run
22:08:34 FAIL chrome.docker: Some tasks failed to run
```

**Comment by aigoncharov** [comment]
@jankoritak currently, if I click on the calendar icon of the input, nothing happens. SHould we add `pointer-events: none`?
image

**Comment by aigoncharov** [comment]
There is a black outline when you click on a date and hold the button .

https://user-images.githubusercontent.com/12794628/109624837-b4bf4980-7b4f-11eb-9f8d-8b1bc23e5301.mp4

**Comment by aigoncharov** [comment]
@jankoritak should we somehow dim the inactive dates?

**Comment by jankoritak** [comment]
Thanks for generating the screenshots for me @aigoncharov!

Will look into the issue with priority.

**Review by aigoncharov — APPROVED** [review]
LGTM!

**Pull request merged**
