### PR TITLE
update(datepicker): remove react-datepicker from peer deps

### PR DESCRIPTION
**Pull request by fantkolja**
In my opinion, the additional peer dependency makes the lib less flexible and will make future upgrades more difficult.
This is a suggestion on how to omit it.

### CODE REVIEW

**Comment by aigoncharov** [comment]
@fantkolja have you tried it? I experimented with something like it. Since npm tries to keep the folder structure flat,  `react- datepicker` is usually installed not in the child folder of `hazelcast/ui`, but in the neighbor folder.
So in your project you will most probably have something like this:
- yourProject 
  - node_module
    - @hazelcast/ui
    - react-datepicker 
    
As you can see, react-datepicker and hazelcast/ui are on the same level. To my best knowledge, SCSS wasn't able to resolve react-datepicker stylesheet in this folder layout. Does it work for you in the cloud?

**Comment by fantkolja** [comment]
> @fantkolja have you tried it? I experimented with something like it. Since npm tries to keep the folder structure flat, `react- datepicker` is usually installed not in the child folder of `hazelcast/ui`, but in the neighbor folder.
> So in your project you will most probably have something like this:
> 
> * yourProject
>   
>   * node_module
>     
>     * @hazelcast/ui
>     * react-datepicker
> 
> As you can see, react-datepicker and hazelcast/ui are on the same level. To my best knowledge, SCSS wasn't able to resolve react-datepicker stylesheet in this folder layout. Does it work for you in the cloud?

But since it uses webpack modules resolving mechanism ("borrowed") from NodeJS it looks up the `node_modules` going upwards first trying to resolve the package in those folders. so in your scheme, it will first find `yourProject/node_modules` and then resolve `react-datepicker` in that folder.

Tried with our app (by importing `import '@hazelcast/ui/styles/datepicker.scss';` and it worked, styles were applied.

**Comment by aigoncharov** [comment]
@danad02 @jankoritak @utkukaratas  could you try this fix before merging it in MC first?

**Comment by jankoritak** [comment]
Seems to be working fine on MC-side. 👍

**Review by jvorcak — APPROVED** [review]

**Pull request merged**
