### PR TITLE
hotfix multiselect disabled state chip color

### LINKED ISSUE #201: [Core UI] Readonly Multiselect looks off
image

Should we dim the items somehow?

### PR DESCRIPTION
**Pull request by utkukaratas**
fixes #201

### CODE REVIEW

**Review by aigoncharov — APPROVED** [review]
LGTM!
BTW, do you think we need to color the X icons in grey as well?

**Comment by utkukaratas** [comment]
@aigoncharov good idea, left the text color intact though. let's cc @pawelklasa to give us the green:

image

**Comment by pawelklasa** [comment]
Do we need a disabled state for this?

**Comment by aigoncharov** [comment]
> Do we need a disabled state for this? @utkukaratas

@pawelklasa yeah. The goal is to make it disabled. Let us know if what we have done at this point is ok or please provide some design guidance on what to change. Thnx!

**Review by danad02 — APPROVED** [review]

**Comment by pawelklasa** [comment]
Hi, @utkukaratas. I suggest we use grey-text for the close icon. I am not so keen on using disabled components and will try to eradicate them with time. So as long as the contrast for fonts and icons is enough, I am happy.

**Pull request merged**
